### PR TITLE
Bootstrap Theme - Second Iteration

### PR DESCRIPTION
**Pull request by stephenrichter**
This iteration contains a few new changes:
1. **New homepage** - I have deviated slightly from the Homepage Mockup, although it contains the same content. As discussed, there are 2 main target audiences for the site and I've tried to bring that through in a more clear, concise way. Further discussion here may help, and we can easily change it to closer match the Homepage Mockup.
2. **Cards Component** - As requested, the Cards component has been extended to feature a few new layouts. This component has been back-ported from Bootstrap 4 and will act the same way.
3. **Colours** - Colours have been changed to show a bit more vibrance. I should have a colour palette available shortly to discuss and to extend the range of colour options available to developers.
4. **Footer** - A evenly distributed, responsive footer has been added.

If you have any questions, let me know and I'll continue to improve upon the theme based on feedback from the Gov team and the community.

### CODE REVIEW

**Comment by lmullane** [comment]
Hi @stephenrichter,

Thanks for the this. Here's my initial feedback.

1. The list pages are a big improvement. The theme is working nicely here.

2. For the static pages, I'm curious why you decided to put the menu on the right?

3. In the footer, please add links for the disclaimer, privacy, accessibility and copyright. 
In the Events and News section on the landing page, I prefer a list of events and blogs like @mark-a-wilson created in the mockup https://projects.invisionapp.com/share/658FMUPUN#/screens/185693619_C_Homepage rather than the having one blog with an intro paragraph. Using just headings for this section is a nice visual break from some of the text elsewhere on the page.

4. At the top of the landing page, could we break up the goals as bullets?

5. Can we find a different colour for the logo and the BC Developers Exchange to better fit the palette?

6. While we may go to persona driven development in the future, let's go without the cards for developers and government (they can stay on the nav bar) for this iteration. Happy to chat about the reasons in more detail if needed.

7. All of the partner logos will need to be in colour as we do not have the rights to modify them. Alternatively we will need to ask for their official grey scale versions. I like the coloured ones regardless. 

Really like the work you are doing here!

Cheers,

Loren

**Comment by stephenrichter** [comment]
@lmullane,

Thanks for the feedback. My thoughts:

1. **List Pages** - Good to hear. I think the lists are nice and clean. Through the theme, there is also the option for your developers to add logos for each partner.
2. **Static Pages** - The static page Table of Contents was replicated from Bootstrap (http://v4-alpha.getbootstrap.com/getting-started/introduction/#quick-start). From a UX perspective, I would mention the headings and text are the most important content on the static pages, while the table of contents is secondary and supportive to this. For that reason, I left the Table of Contents nav menu on the right. However, I can understand both approaches and changing the menu side is **very easy** with this theme.
3. **Homepage** - Thanks for this link. I want to check if this is the latest copy of the Homepage mockup? I've been working off the PDF shared in the original Issue, however, this Invision mockup seems a lot tighter.
4. **Goals as Bullets** - Definitely, or I can replicate the Homepage mockup (see item above).
5. **Logo Colour** - I will add the full colour palette to the Theme page this evening. I can try to Photoshop the right colours for the logo, however this may be best left to whoever is the original creator of the logo files.
6. **Persona Cards** - Sounds good. I will change to match the Homepage mockup. Let's chat about this afterwards if you'd like.
7. **Partner Logos** - That makes sense. I will change to the coloured logos and include the full list of them.

Thanks and please feel free to add any further changes you see in this thread. I should be sending the next PR through this evening.

Stephen

**Comment by lmullane** [comment]
Hi @stephenrichter, 

2. Thanks for the explanation on the right Table of Contents. Let's leave it.
3. It looks like I muddied the waters with a different mockup. The one in the issue is the newer version. I just preferred the list of blogs.
5. Let's leave the logo colour with the creator of the file.

A couple of additional questions.

1. In mockup and your first iteration there was a section for Kick-Start. Any reason why this is not part of the second iteration?

2. In the mockup there is a place for testimonials. Did you @mark-a-wilson discuss leaving this out?

Looking forward to the next iteration.

Cheers,

Loren

**Comment by stephenrichter** [comment]
@lmullane - I have incorporated all your questions/comments from this Pull Request in Pull Request #7 

The new PR brings back more of the original mockup PDF sections and features.

Cheers!

**Comment by lmullane** [comment]
Thanks, @stephenrichter. I will have a look today.

**Pull request merged**
